# Default values for mysql-galera.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloud: "do" # may be "do", "aws", "local"
namespace: mysql-galera
replicaCount: 3
podManagementPolicy: Parallel
updateStrategy: RollingUpdate

image:
  registry: docker.io
  repository: codership/mysql-galera-test
  pullPolicy: Always
  tag: 8.0.34
  digest: ""
  mysqlID: 1000 # need for chown the datadir

datadir:
  storageclass: "" # specify for on-prem and other custom installations.
  size: 5Gi

container:
  limits:
    memory: 4Gi
    cpu: 1

galera:
  replication:
    method: rsync
  bootstrap:
    forceBootstrap: 0 # must be 0 or 1
    bootstrapFromNode: 1

mysql:
  rootpw: uFdpg5HgtJ!!
  user:
    name: test
    password: test123!
