# Example StorageClass to utilize minikube's hostPath driver for testing
# purposes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "mysql-galera.fullname" . }}-minikube-sc
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
reclaimPolicy: Retain
